# Generated by Django 4.0.2 on 2022-05-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='shoes_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='shoes_disc',
            new_name='disc',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='shoes_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='shoes_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='shoes_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='shoes_disc',
            new_name='disc',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='shoes_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='shoes_price',
            new_name='price',
        ),
    ]
