# Generated by Django 4.0.2 on 2022-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_shoes_category_mobile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
