# Generated by Django 4.0.3 on 2022-05-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_mobile_product_image_shoes_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='baby_mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='footwear_mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=150)),
                ('disc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='shoes_mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='shoes',
        ),
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='disc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
